import SideBar from "@/components/sidebar";
import "./globals.css";
import TopBar from "@/components/topbar";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <TopBar />
        <SideBar />
        {children}
      </body>
    </html>
  );
}
